apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/MuhanedYahya/argocd-lab.git
    targetRevision: default
    path: manifests/web-color
  syncPolicy:
    automated:
      prune: true
      selfHeal: true