apiVersion: v1
kind: Service
metadata:
  name: web-color
  labels:
    app: web-color
spec:
  selector:
    app: web-color
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
